// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.29.3
// source: modules/product/productPb/productPb.proto

package go_microservices

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ProductGrpcServiceClient is the client API for ProductGrpcService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProductGrpcServiceClient interface {
	FindProductsInIds(ctx context.Context, in *FindProductsInIdsReq, opts ...grpc.CallOption) (*FindProductsInIdsRes, error)
}

type productGrpcServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProductGrpcServiceClient(cc grpc.ClientConnInterface) ProductGrpcServiceClient {
	return &productGrpcServiceClient{cc}
}

func (c *productGrpcServiceClient) FindProductsInIds(ctx context.Context, in *FindProductsInIdsReq, opts ...grpc.CallOption) (*FindProductsInIdsRes, error) {
	out := new(FindProductsInIdsRes)
	err := c.cc.Invoke(ctx, "/ProductGrpcService/FindProductsInIds", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProductGrpcServiceServer is the server API for ProductGrpcService service.
// All implementations must embed UnimplementedProductGrpcServiceServer
// for forward compatibility
type ProductGrpcServiceServer interface {
	FindProductsInIds(context.Context, *FindProductsInIdsReq) (*FindProductsInIdsRes, error)
	mustEmbedUnimplementedProductGrpcServiceServer()
}

// UnimplementedProductGrpcServiceServer must be embedded to have forward compatible implementations.
type UnimplementedProductGrpcServiceServer struct {
}

func (UnimplementedProductGrpcServiceServer) FindProductsInIds(context.Context, *FindProductsInIdsReq) (*FindProductsInIdsRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindProductsInIds not implemented")
}
func (UnimplementedProductGrpcServiceServer) mustEmbedUnimplementedProductGrpcServiceServer() {}

// UnsafeProductGrpcServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProductGrpcServiceServer will
// result in compilation errors.
type UnsafeProductGrpcServiceServer interface {
	mustEmbedUnimplementedProductGrpcServiceServer()
}

func RegisterProductGrpcServiceServer(s grpc.ServiceRegistrar, srv ProductGrpcServiceServer) {
	s.RegisterService(&ProductGrpcService_ServiceDesc, srv)
}

func _ProductGrpcService_FindProductsInIds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindProductsInIdsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductGrpcServiceServer).FindProductsInIds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ProductGrpcService/FindProductsInIds",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductGrpcServiceServer).FindProductsInIds(ctx, req.(*FindProductsInIdsReq))
	}
	return interceptor(ctx, in, info, handler)
}

// ProductGrpcService_ServiceDesc is the grpc.ServiceDesc for ProductGrpcService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProductGrpcService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ProductGrpcService",
	HandlerType: (*ProductGrpcServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindProductsInIds",
			Handler:    _ProductGrpcService_FindProductsInIds_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "modules/product/productPb/productPb.proto",
}
